/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dhafintaufiqi21 (https://sketchfab.com/dhafintaufiqi21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/psu-power-supply-unit-69ccd1be3a77497cb2acc9e39e7c52b3
Title: PSU Power Supply Unit
*/


import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'


type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
  }
  materials: {
    putih: THREE.MeshStandardMaterial
    abuabu: THREE.MeshStandardMaterial
    hitam: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['put.001']: THREE.MeshStandardMaterial
    ['put.002']: THREE.MeshStandardMaterial
    ['put.003']: THREE.MeshStandardMaterial
    ['put.004']: THREE.MeshStandardMaterial
    ['put.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
  }
}


export default function Psu(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(require ( '../assets/Psu.glb') ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.002, -0.631, -0.197]}
        rotation={[1.619, -0.349, 0.393]}
        scale={[0.286, 6.189, 0.221]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group
        position={[-5.126, -0.631, -0.197]}
        rotation={[1.619, -0.349, 0.393]}
        scale={[0.268, 6.774, 0.114]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials['Material.010']}
        />
      </group>
      <group
        position={[3.345, -0.631, -0.197]}
        rotation={[1.619, -0.349, 0.393]}
        scale={[0.286, 6.189, 0.221]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_60.geometry}
          material={materials['Material.013']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.putih}
        position={[0.035, 3.148, -0.004]}
        rotation={[0, 0.175, Math.PI]}
        scale={5.244}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.abuabu}
        scale={[9.946, 5.219, 9.946]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.abuabu}
        position={[0, 5.017, 0]}
        scale={[1.947, 0.047, 1.947]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.abuabu}
        position={[-7.904, 4.659, 8.965]}
        rotation={[0, 0, 3.141]}
        scale={0.472}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.hitam}
        position={[-5.293, -3.325, -8.263]}
        rotation={[0, 0, -Math.PI]}
        scale={[1.78, 1.448, 2.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.hitam}
        position={[-5.336, -0.002, -8.689]}
        scale={[1.919, 1.569, 1.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.004']}
        position={[-5.293, -3.218, -10.257]}
        rotation={[-0.005, 0.156, -3.141]}
        scale={[1.524, 1.161, 0.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.004']}
        position={[-8.15, -1.997, 9.208]}
        scale={[1.031, 0.623, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.abuabu}
        position={[-7.796, 4.634, -8.871]}
        rotation={[0, 0, 3.141]}
        scale={0.507}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.abuabu}
        position={[7.915, 4.634, -8.871]}
        rotation={[0, 0, 3.141]}
        scale={0.507}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.abuabu}
        position={[7.915, 4.634, 8.961]}
        rotation={[0, 0, 3.141]}
        scale={0.507}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.Material}
        position={[7.926, 4.901, -8.865]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.Material}
        position={[-7.802, 4.901, -8.885]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.Material}
        position={[-7.906, 4.901, 8.95]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.Material}
        position={[7.916, 4.901, 8.95]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.hitam}
        position={[-7.802, 0, -10.11]}
        rotation={[-1.567, 0, 0]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.hitam}
        position={[-2.861, 0, -10.11]}
        rotation={[-1.567, 0, 0]}
        scale={[0.081, 0.239, 0.081]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.material}
        position={[-4.31, 0.358, -8.713]}
        scale={[0.082, 0.239, 1.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.material}
        position={[-6.329, 0.358, -8.713]}
        scale={[0.082, 0.239, 1.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.material}
        position={[-5.383, -0.519, -8.713]}
        scale={[0.082, 0.239, 1.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.hitam}
        position={[-9.888, 0, 0]}
        scale={[0.178, 2.45, 9.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.hitam}
        position={[9.87, 0, 0]}
        scale={[0.178, 2.45, 9.823]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials['Material.002']}
        position={[-0.255, 0, 9.249]}
        scale={[9.449, 4.233, 0.075]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials['Material.002']}
        position={[10.312, -1.88, 8.977]}
        rotation={[1.571, 0.007, -1.586]}
        scale={5.224}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.material}
        position={[-4.772, -2.49, -10.791]}
        rotation={[0.015, -1.338, -1.556]}
        scale={0.813}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials['put.001']}
        position={[-6.634, -2.776, -10.499]}
        rotation={[0.015, -1.338, -1.556]}
        scale={0.864}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials['put.002']}
        position={[-7.938, 3.041, 9.965]}
        rotation={[1.6, -0.001, -0.003]}
        scale={0.711}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials['put.003']}
        position={[2.15, 3.041, 9.965]}
        rotation={[1.6, -0.001, -0.003]}
        scale={0.711}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials['put.004']}
        position={[2.15, -0.742, 9.965]}
        rotation={[1.6, -0.001, -0.003]}
        scale={0.711}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials['put.005']}
        position={[-8.068, -0.8, 9.966]}
        rotation={[1.6, -0.001, -0.003]}
        scale={0.711}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials['Material.003']}
        position={[-10.111, -0.818, -8.759]}
        rotation={[1.571, -0.007, 1.572]}
        scale={1.846}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.material_0}
        position={[-7.904, 16.415, 8.965]}
        rotation={[0, 0, 3.141]}
        scale={0.303}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.material_0}
        position={[0.039, 0.39, 11.524]}
        scale={[0.284, 0.247, 0.284]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.material_0}
        position={[-0.647, 0.39, 11.524]}
        scale={[0.284, 0.247, 0.284]}
      />
    </group>
  )
}


useGLTF.preload(require ( '../assets/Psu.glb') );